name: echovision
description: "EchoVision (YankıGörüş) - Zero-UI AI Assistant for the Visually Impaired"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  tflite_flutter: ^0.12.0
  image: ^4.2.0
  flutter_tts: ^4.2.0
  vibration: ^2.0.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  sensors_plus: ^6.1.1
  http: ^1.2.0
  path_provider: ^2.1.5
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/models/
    - assets/models/yolo11n.tflite
    - assets/models/labelmap.txt
