import 'package:camera/camera.dart';
import 'package:google_mlkit_object_detection/google_mlkit_object_detection.dart';
import 'package:google_mlkit_image_labeling/google_mlkit_image_labeling.dart';

/// ML Kit Object Detection & Image Labeling Service.
/// Supports hundreds of object categories with Turkish translations.
/// Works completely offline with on-device processing.
class MLKitDetectionService {
  ObjectDetector? _objectDetector;
  ImageLabeler? _imageLabeler;
  bool _isInitialized = false;

  bool get isInitialized => _isInitialized;

  Future<void> initialize() async {
    try {
      // Object Detector - detects objects with bounding boxes
      final objectOptions = ObjectDetectorOptions(
        mode: DetectionMode.single,
        classifyObjects: true,
        multipleObjects: true,
      );
      _objectDetector = ObjectDetector(options: objectOptions);

      // Image Labeler - provides detailed labels for the entire image
      // Lower threshold to detect more objects
      final labelerOptions = ImageLabelerOptions(confidenceThreshold: 0.3);
      _imageLabeler = ImageLabeler(options: labelerOptions);

      _isInitialized = true;
      print('MLKit Detection: Service initialized');
    } catch (e) {
      print('MLKit Detection init error: $e');
      _isInitialized = false;
    }
  }

  /// Analyze image and return Turkish descriptions of detected objects.
  Future<List<String>> analyzeImage(XFile imageFile) async {
    if (!_isInitialized) return [];

    try {
      final inputImage = InputImage.fromFilePath(imageFile.path);
      final results = <String>{};

      // 1. Object Detection (with bounding boxes)
      if (_objectDetector != null) {
        final objects = await _objectDetector!.processImage(inputImage);
        for (final obj in objects) {
          for (final label in obj.labels) {
            final turkishName = _translateToTurkish(label.text);
            if (turkishName.isNotEmpty) {
              results.add(turkishName);
              print('MLKit Object: ${label.text} -> $turkishName (${(label.confidence * 100).toInt()}%)');
            }
          }
        }
      }

      // 2. Image Labeling (for additional context)
      if (_imageLabeler != null) {
        final labels = await _imageLabeler!.processImage(inputImage);
        for (final label in labels) {
          final turkishName = _translateToTurkish(label.label);
          if (turkishName.isNotEmpty) {
            results.add(turkishName);
            print('MLKit Label: ${label.label} -> $turkishName (${(label.confidence * 100).toInt()}%)');
          }
        }
      }

      return results.take(15).toList();
    } catch (e) {
      print('MLKit Detection Error: $e');
      return [];
    }
  }

  /// Translate English label to Turkish
  static String translateToTurkish(String englishLabel) {
    final key = englishLabel.toLowerCase().trim();
    return _turkishLabels[key] ?? ''; // Returns empty string if not in dictionary to cancel English
  }

  String _translateToTurkish(String englishLabel) {
    return translateToTurkish(englishLabel);
  }

  Future<void> dispose() async {
    await _objectDetector?.close();
    await _imageLabeler?.close();
    _objectDetector = null;
    _imageLabeler = null;
    _isInitialized = false;
  }
}

// ─── Comprehensive Turkish Labels (700+ translations) ────────────────────────

const Map<String, String> _turkishLabels = {
  // ═══════════════════════════════════════════════════════════════════════════
  // PEOPLE & BODY PARTS
  // ═══════════════════════════════════════════════════════════════════════════
  'person': 'kişi',
  'man': 'erkek',
  'woman': 'kadın',
  'child': 'çocuk',
  'baby': 'bebek',
  'boy': 'erkek çocuk',
  'girl': 'kız çocuk',
  'teenager': 'genç',
  'adult': 'yetişkin',
  'elderly': 'yaşlı',
  'face': 'yüz',
  'head': 'baş',
  'hand': 'el',
  'arm': 'kol',
  'leg': 'bacak',
  'foot': 'ayak',
  'eye': 'göz',
  'nose': 'burun',
  'mouth': 'ağız',
  'ear': 'kulak',
  'hair': 'saç',
  'finger': 'parmak',
  'human face': 'insan yüzü',
  'human body': 'insan vücudu',
  'human hand': 'insan eli',
  'human arm': 'insan kolu',
  'human leg': 'insan bacağı',
  'crowd': 'kalabalık',
  'group': 'grup',
  'family': 'aile',

  // ═══════════════════════════════════════════════════════════════════════════
  // VEHICLES
  // ═══════════════════════════════════════════════════════════════════════════
  'vehicle': 'araç',
  'car': 'araba',
  'automobile': 'otomobil',
  'bicycle': 'bisiklet',
  'motorcycle': 'motosiklet',
  'motorbike': 'motosiklet',
  'bus': 'otobüs',
  'truck': 'kamyon',
  'train': 'tren',
  'airplane': 'uçak',
  'aeroplane': 'uçak',
  'aircraft': 'uçak',
  'boat': 'tekne',
  'ship': 'gemi',
  'ferry': 'feribot',
  'yacht': 'yat',
  'helicopter': 'helikopter',
  'taxi': 'taksi',
  'cab': 'taksi',
  'ambulance': 'ambulans',
  'fire truck': 'itfaiye aracı',
  'police car': 'polis arabası',
  'van': 'minibüs',
  'minivan': 'minivan',
  'suv': 'cip',
  'pickup truck': 'kamyonet',
  'scooter': 'scooter',
  'skateboard': 'kaykay',
  'tram': 'tramvay',
  'subway': 'metro',
  'metro': 'metro',
  'trolley': 'troleybüs',
  'carriage': 'fayton',
  'cart': 'el arabası',
  'wagon': 'vagon',
  'trailer': 'römork',
  'tractor': 'traktör',
  'forklift': 'forklift',
  'crane': 'vinç',
  'bulldozer': 'buldozer',
  'excavator': 'ekskavatör',
  'land vehicle': 'kara aracı',
  'watercraft': 'deniz aracı',

  // ═══════════════════════════════════════════════════════════════════════════
  // ANIMALS
  // ═══════════════════════════════════════════════════════════════════════════
  'animal': 'hayvan',
  'dog': 'köpek',
  'cat': 'kedi',
  'bird': 'kuş',
  'horse': 'at',
  'cow': 'inek',
  'sheep': 'koyun',
  'goat': 'keçi',
  'pig': 'domuz',
  'chicken': 'tavuk',
  'rooster': 'horoz',
  'duck': 'ördek',
  'goose': 'kaz',
  'turkey': 'hindi',
  'fish': 'balık',
  'rabbit': 'tavşan',
  'mouse': 'fare',
  'rat': 'sıçan',
  'hamster': 'hamster',
  'squirrel': 'sincap',
  'deer': 'geyik',
  'bear': 'ayı',
  'wolf': 'kurt',
  'fox': 'tilki',
  'lion': 'aslan',
  'tiger': 'kaplan',
  'elephant': 'fil',
  'giraffe': 'zürafa',
  'zebra': 'zebra',
  'monkey': 'maymun',
  'gorilla': 'goril',
  'snake': 'yılan',
  'lizard': 'kertenkele',
  'turtle': 'kaplumbağa',
  'tortoise': 'kara kaplumbağası',
  'frog': 'kurbağa',
  'insect': 'böcek',
  'butterfly': 'kelebek',
  'bee': 'arı',
  'spider': 'örümcek',
  'ant': 'karınca',
  'fly': 'sinek',
  'mosquito': 'sivrisinek',
  'cockroach': 'hamamböceği',
  'eagle': 'kartal',
  'hawk': 'şahin',
  'owl': 'baykuş',
  'parrot': 'papağan',
  'penguin': 'penguen',
  'swan': 'kuğu',
  'pigeon': 'güvercin',
  'dove': 'kumru',
  'crow': 'karga',
  'sparrow': 'serçe',
  'seagull': 'martı',
  'whale': 'balina',
  'dolphin': 'yunus',
  'shark': 'köpekbalığı',
  'octopus': 'ahtapot',
  'jellyfish': 'denizanası',
  'crab': 'yengeç',
  'lobster': 'ıstakoz',
  'shrimp': 'karides',
  'snail': 'salyangoz',
  'worm': 'solucan',
  'camel': 'deve',
  'donkey': 'eşek',
  'mule': 'katır',
  'buffalo': 'manda',
  'bull': 'boğa',
  'panda': 'panda',
  'koala': 'koala',
  'kangaroo': 'kanguru',
  'hedgehog': 'kirpi',
  'pet': 'evcil hayvan',

  // ═══════════════════════════════════════════════════════════════════════════
  // FOOD & DRINKS
  // ═══════════════════════════════════════════════════════════════════════════
  'food': 'yiyecek',
  'drink': 'içecek',
  'fruit': 'meyve',
  'vegetable': 'sebze',
  'apple': 'elma',
  'banana': 'muz',
  'orange': 'portakal',
  'lemon': 'limon',
  'grape': 'üzüm',
  'strawberry': 'çilek',
  'watermelon': 'karpuz',
  'melon': 'kavun',
  'peach': 'şeftali',
  'pear': 'armut',
  'cherry': 'kiraz',
  'plum': 'erik',
  'apricot': 'kayısı',
  'fig': 'incir',
  'pomegranate': 'nar',
  'mango': 'mango',
  'pineapple': 'ananas',
  'kiwi': 'kivi',
  'coconut': 'hindistan cevizi',
  'avocado': 'avokado',
  'tomato': 'domates',
  'potato': 'patates',
  'onion': 'soğan',
  'garlic': 'sarımsak',
  'carrot': 'havuç',
  'cucumber': 'salatalık',
  'pepper': 'biber',
  'eggplant': 'patlıcan',
  'aubergine': 'patlıcan',
  'zucchini': 'kabak',
  'squash': 'balkabağı',
  'pumpkin': 'bal kabağı',
  'broccoli': 'brokoli',
  'cauliflower': 'karnabahar',
  'cabbage': 'lahana',
  'lettuce': 'marul',
  'spinach': 'ıspanak',
  'celery': 'kereviz',
  'corn': 'mısır',
  'pea': 'bezelye',
  'bean': 'fasulye',
  'mushroom': 'mantar',
  'bread': 'ekmek',
  'rice': 'pilav',
  'pasta': 'makarna',
  'noodle': 'erişte',
  'cheese': 'peynir',
  'butter': 'tereyağı',
  'egg': 'yumurta',
  'meat': 'et',
  'beef': 'sığır eti',
  'chicken meat': 'tavuk eti',
  'lamb': 'kuzu eti',
  'pork': 'domuz eti',
  'sausage': 'sosis',
  'bacon': 'pastırma',
  'ham': 'jambon',
  'steak': 'biftek',
  'burger': 'hamburger',
  'hamburger': 'hamburger',
  'hot dog': 'sosisli',
  'pizza': 'pizza',
  'sandwich': 'sandviç',
  'salad': 'salata',
  'soup': 'çorba',
  'cake': 'pasta',
  'cookie': 'kurabiye',
  'biscuit': 'bisküvi',
  'chocolate': 'çikolata',
  'candy': 'şeker',
  'ice cream': 'dondurma',
  'donut': 'donut',
  'doughnut': 'donut',
  'pie': 'turta',
  'pancake': 'pankek',
  'waffle': 'waffle',
  'croissant': 'kruvasan',
  'bagel': 'simit',
  'pretzel': 'çubuk kraker',
  'popcorn': 'patlamış mısır',
  'chips': 'cips',
  'fries': 'patates kızartması',
  'french fries': 'patates kızartması',
  'water': 'su',
  'milk': 'süt',
  'juice': 'meyve suyu',
  'coffee': 'kahve',
  'tea': 'çay',
  'soda': 'gazoz',
  'cola': 'kola',
  'beer': 'bira',
  'wine': 'şarap',
  'alcohol': 'alkol',
  'cocktail': 'kokteyl',
  'smoothie': 'smoothie',
  'yogurt': 'yoğurt',
  'honey': 'bal',
  'jam': 'reçel',
  'sauce': 'sos',
  'ketchup': 'ketçap',
  'mayonnaise': 'mayonez',
  'mustard': 'hardal',
  'salt': 'tuz',
  'sugar': 'şeker',
  'flour': 'un',
  'oil': 'yağ',
  'olive oil': 'zeytinyağı',
  'vinegar': 'sirke',
  'spice': 'baharat',
  'nut': 'kuruyemiş',
  'almond': 'badem',
  'walnut': 'ceviz',
  'peanut': 'yer fıstığı',
  'pistachio': 'antep fıstığı',
  'hazelnut': 'fındık',
  'baked goods': 'unlu mamul',
  'dessert': 'tatlı',
  'snack': 'atıştırmalık',
  'breakfast': 'kahvaltı',
  'lunch': 'öğle yemeği',
  'dinner': 'akşam yemeği',
  'meal': 'yemek',
  'fast food': 'fast food',

  // ═══════════════════════════════════════════════════════════════════════════
  // FURNITURE & HOME ITEMS
  // ═══════════════════════════════════════════════════════════════════════════
  'furniture': 'mobilya',
  'chair': 'sandalye',
  'table': 'masa',
  'desk': 'çalışma masası',
  'bed': 'yatak',
  'sofa': 'kanepe',
  'couch': 'kanepe',
  'armchair': 'koltuk',
  'bench': 'bank',
  'stool': 'tabure',
  'shelf': 'raf',
  'bookshelf': 'kitaplık',
  'cabinet': 'dolap',
  'wardrobe': 'gardırop',
  'closet': 'dolap',
  'drawer': 'çekmece',
  'chest': 'sandık',
  'mirror': 'ayna',
  'lamp': 'lamba',
  'chandelier': 'avize',
  'curtain': 'perde',
  'carpet': 'halı',
  'rug': 'kilim',
  'pillow': 'yastık',
  'blanket': 'battaniye',
  'mattress': 'şilte',
  'sheet': 'çarşaf',
  'towel': 'havlu',
  'clock': 'saat',
  'wall clock': 'duvar saati',
  'alarm clock': 'çalar saat',
  'vase': 'vazo',
  'plant pot': 'saksı',
  'potted plant': 'saksı bitkisi',
  'flower pot': 'çiçek saksısı',
  'picture frame': 'resim çerçevesi',
  'painting': 'tablo',
  'poster': 'poster',
  'candle': 'mum',
  'fan': 'vantilatör',
  'heater': 'ısıtıcı',
  'radiator': 'radyatör',
  'air conditioner': 'klima',
  'fireplace': 'şömine',
  'door': 'kapı',
  'window': 'pencere',
  'floor': 'zemin',
  'wall': 'duvar',
  'ceiling': 'tavan',
  'roof': 'çatı',
  'stairs': 'merdiven',
  'staircase': 'merdiven boşluğu',
  'balcony': 'balkon',
  'terrace': 'teras',
  'garden': 'bahçe',
  'yard': 'avlu',

  // ═══════════════════════════════════════════════════════════════════════════
  // KITCHEN ITEMS
  // ═══════════════════════════════════════════════════════════════════════════
  'kitchen': 'mutfak',
  'refrigerator': 'buzdolabı',
  'fridge': 'buzdolabı',
  'freezer': 'dondurucu',
  'oven': 'fırın',
  'stove': 'ocak',
  'microwave': 'mikrodalga',
  'toaster': 'tost makinesi',
  'blender': 'blender',
  'mixer': 'mikser',
  'kettle': 'su ısıtıcısı',
  'coffee maker': 'kahve makinesi',
  'dishwasher': 'bulaşık makinesi',
  'sink': 'lavabo',
  'faucet': 'musluk',
  'tap': 'musluk',
  'plate': 'tabak',
  'dish': 'tabak',
  'bowl': 'kase',
  'cup': 'fincan',
  'mug': 'kupa',
  'glass': 'bardak',
  'bottle': 'şişe',
  'jar': 'kavanoz',
  'can': 'kutu',
  'fork': 'çatal',
  'knife': 'bıçak',
  'spoon': 'kaşık',
  'chopsticks': 'yemek çubukları',
  'cutting board': 'kesme tahtası',
  'pan': 'tava',
  'pot': 'tencere',
  'saucepan': 'küçük tencere',
  'wok': 'wok',
  'baking tray': 'fırın tepsisi',
  'spatula': 'spatula',
  'ladle': 'kepçe',
  'whisk': 'çırpıcı',
  'grater': 'rende',
  'colander': 'süzgeç',
  'strainer': 'kevgir',
  'rolling pin': 'oklava',
  'scale': 'terazi',
  'measuring cup': 'ölçü kabı',
  'napkin': 'peçete',
  'tablecloth': 'masa örtüsü',
  'apron': 'önlük',
  'container': 'kap',
  'food container': 'yemek kabı',
  'lid': 'kapak',
  'tray': 'tepsi',
  'platter': 'servis tabağı',
  'wine glass': 'şarap kadehi',
  'champagne glass': 'şampanya kadehi',
  'pitcher': 'sürahi',
  'jug': 'testi',
  'teapot': 'çaydanlık',
  'coffee pot': 'cezve',
  'sugar bowl': 'şekerlik',
  'salt shaker': 'tuzluk',
  'pepper shaker': 'biberlik',

  // ═══════════════════════════════════════════════════════════════════════════
  // BATHROOM ITEMS
  // ═══════════════════════════════════════════════════════════════════════════
  'bathroom': 'banyo',
  'toilet': 'tuvalet',
  'bathtub': 'küvet',
  'shower': 'duş',
  'bidet': 'bide',
  'soap': 'sabun',
  'shampoo': 'şampuan',
  'toothbrush': 'diş fırçası',
  'toothpaste': 'diş macunu',
  'razor': 'tıraş bıçağı',
  'comb': 'tarak',
  'brush': 'fırça',
  'hair dryer': 'saç kurutma makinesi',
  'hairdryer': 'fön makinesi',
  'toilet paper': 'tuvalet kağıdı',
  'tissue': 'kağıt mendil',
  'cosmetics': 'kozmetik',
  'makeup': 'makyaj',
  'perfume': 'parfüm',
  'deodorant': 'deodorant',
  'lotion': 'losyon',
  'cream': 'krem',
  'sunscreen': 'güneş kremi',
  'nail polish': 'oje',
  'lipstick': 'ruj',
  'mascara': 'maskara',
  'bathroom scale': 'banyo tartısı',

  // ═══════════════════════════════════════════════════════════════════════════
  // ELECTRONICS
  // ═══════════════════════════════════════════════════════════════════════════
  'electronics': 'elektronik',
  'phone': 'telefon',
  'telephone': 'telefon',
  'cell phone': 'cep telefonu',
  'mobile phone': 'cep telefonu',
  'smartphone': 'akıllı telefon',
  'computer': 'bilgisayar',
  'laptop': 'dizüstü bilgisayar',
  'desktop': 'masaüstü bilgisayar',
  'monitor': 'monitör',
  'screen': 'ekran',
  'display': 'görüntü ekranı',
  'keyboard': 'klavye',
  'computer mouse': 'bilgisayar faresi',
  'printer': 'yazıcı',
  'scanner': 'tarayıcı',
  'projector': 'projeksiyon',
  'camera': 'kamera',
  'webcam': 'web kamerası',
  'microphone': 'mikrofon',
  'speaker': 'hoparlör',
  'headphones': 'kulaklık',
  'earphones': 'kulak içi kulaklık',
  'earbuds': 'kablosuz kulaklık',
  'television': 'televizyon',
  'tv': 'televizyon',
  'remote': 'kumanda',
  'remote control': 'uzaktan kumanda',
  'tablet': 'tablet',
  'ipad': 'tablet',
  'e-reader': 'e-kitap okuyucu',
  'smartwatch': 'akıllı saat',
  'watch': 'kol saati',
  'wristwatch': 'bilek saati',
  'charger': 'şarj aleti',
  'cable': 'kablo',
  'wire': 'tel',
  'plug': 'fiş',
  'outlet': 'priz',
  'socket': 'soket',
  'switch': 'anahtar',
  'light switch': 'ışık anahtarı',
  'battery': 'pil',
  'flashlight': 'el feneri',
  'torch': 'meşale',
  'radio': 'radyo',
  'dvd player': 'dvd oynatıcı',
  'game console': 'oyun konsolu',
  'playstation': 'playstation',
  'xbox': 'xbox',
  'nintendo': 'nintendo',
  'joystick': 'oyun kolu',
  'controller': 'oyun kumandası',
  'video game': 'video oyunu',
  'drone': 'drone',
  'robot': 'robot',

  // ═══════════════════════════════════════════════════════════════════════════
  // CLOTHING & ACCESSORIES
  // ═══════════════════════════════════════════════════════════════════════════
  'clothing': 'giysi',
  'clothes': 'kıyafet',
  'shirt': 'gömlek',
  't-shirt': 'tişört',
  'blouse': 'bluz',
  'sweater': 'kazak',
  'sweatshirt': 'sweatshirt',
  'hoodie': 'kapşonlu',
  'jacket': 'ceket',
  'coat': 'palto',
  'blazer': 'blazer ceket',
  'suit': 'takım elbise',
  'dress': 'elbise',
  'skirt': 'etek',
  'pants': 'pantolon',
  'trousers': 'pantolon',
  'jeans': 'kot pantolon',
  'shorts': 'şort',
  'underwear': 'iç çamaşırı',
  'bra': 'sütyen',
  'socks': 'çorap',
  'stockings': 'külotlu çorap',
  'pajamas': 'pijama',
  'robe': 'bornoz',
  'swimsuit': 'mayo',
  'bikini': 'bikini',
  'shoe': 'ayakkabı',
  'shoes': 'ayakkabılar',
  'boot': 'bot',
  'boots': 'çizme',
  'sandal': 'sandalet',
  'sandals': 'sandaletler',
  'sneaker': 'spor ayakkabı',
  'sneakers': 'spor ayakkabılar',
  'heel': 'topuklu',
  'heels': 'topuklu ayakkabı',
  'slipper': 'terlik',
  'slippers': 'terlikler',
  'hat': 'şapka',
  'cap': 'kasket',
  'beanie': 'bere',
  'helmet': 'kask',
  'scarf': 'atkı',
  'tie': 'kravat',
  'bow tie': 'papyon',
  'belt': 'kemer',
  'glove': 'eldiven',
  'gloves': 'eldivenler',
  'mitten': 'parmaksız eldiven',
  'sunglasses': 'güneş gözlüğü',
  'glasses': 'gözlük',
  'eyeglasses': 'numaralı gözlük',
  'spectacles': 'optik gözlük',
  'bag': 'çanta',
  'handbag': 'el çantası',
  'purse': 'cüzdan',
  'wallet': 'erkek cüzdanı',
  'backpack': 'sırt çantası',
  'suitcase': 'bavul',
  'luggage': 'bagaj',
  'briefcase': 'evrak çantası',
  'umbrella': 'şemsiye',
  'jewelry': 'takı',
  'jewellery': 'mücevher',
  'ring': 'yüzük',
  'necklace': 'kolye',
  'bracelet': 'bilezik',
  'earring': 'küpe',
  'earrings': 'küpeler',
  'brooch': 'broş',
  'pendant': 'pandantif',
  'chain': 'zincir',

  // ═══════════════════════════════════════════════════════════════════════════
  // OFFICE & SCHOOL SUPPLIES
  // ═══════════════════════════════════════════════════════════════════════════
  'office': 'ofis',
  'school': 'okul',
  'classroom': 'sınıf',
  'book': 'kitap',
  'notebook': 'defter',
  'paper': 'kağıt',
  'document': 'belge',
  'file': 'dosya',
  'folder': 'klasör',
  'envelope': 'zarf',
  'pen': 'kalem',
  'pencil': 'kurşun kalem',
  'marker': 'işaretleyici',
  'highlighter': 'fosforlu kalem',
  'crayon': 'pastel boya',
  'eraser': 'silgi',
  'ruler': 'cetvel',
  'scissors': 'makas',
  'stapler': 'zımba',
  'tape': 'bant',
  'glue': 'yapıştırıcı',
  'paper clip': 'ataş',
  'pin': 'toplu iğne',
  'thumbtack': 'raptiye',
  'calculator': 'hesap makinesi',
  'calendar': 'takvim',
  'whiteboard': 'beyaz tahta',
  'blackboard': 'kara tahta',
  'chalkboard': 'yazı tahtası',
  'chalk': 'tebeşir',
  'globe': 'küre',
  'map': 'harita',
  'chart': 'grafik',
  'diagram': 'diyagram',
  'magazine': 'dergi',
  'newspaper': 'gazete',
  'letter': 'mektup',
  'postcard': 'kartpostal',
  'stamp': 'pul',
  'business card': 'kartvizit',
  'id card': 'kimlik kartı',
  'badge': 'rozet',

  // ═══════════════════════════════════════════════════════════════════════════
  // SPORTS & FITNESS
  // ═══════════════════════════════════════════════════════════════════════════
  'sports': 'spor',
  'ball': 'top',
  'sports ball': 'spor topu',
  'football': 'futbol topu',
  'soccer ball': 'futbol topu',
  'basketball': 'basketbol topu',
  'tennis ball': 'tenis topu',
  'baseball': 'beyzbol topu',
  'volleyball': 'voleybol topu',
  'golf ball': 'golf topu',
  'rugby ball': 'ragbi topu',
  'tennis racket': 'tenis raketi',
  'badminton racket': 'badminton raketi',
  'baseball bat': 'beyzbol sopası',
  'golf club': 'golf sopası',
  'hockey stick': 'hokey sopası',
  'ski': 'kayak',
  'skis': 'kayaklar',
  'snowboard': 'snowboard',
  'surfboard': 'sörf tahtası',
  'frisbee': 'frizbi',
  'kite': 'uçurtma',
  'bike': 'bisiklet',
  'gym': 'spor salonu',
  'weight': 'ağırlık',
  'dumbbell': 'dambıl',
  'barbell': 'halter',
  'treadmill': 'koşu bandı',
  'exercise bike': 'egzersiz bisikleti',
  'yoga mat': 'yoga matı',
  'jump rope': 'ip atlama',
  'boxing glove': 'boks eldiveni',
  'baseball glove': 'beyzbol eldiveni',
  'swimming pool': 'yüzme havuzu',
  'pool': 'havuz',
  'net': 'ağ',
  'goal': 'kale',
  'hoop': 'pota',
  'track': 'pist',
  'court': 'saha',
  'field': 'alan',
  'stadium': 'stadyum',
  'arena': 'arena',
  'medal': 'madalya',
  'trophy': 'kupa',

  // ═══════════════════════════════════════════════════════════════════════════
  // TOOLS & EQUIPMENT
  // ═══════════════════════════════════════════════════════════════════════════
  'tool': 'alet',
  'tools': 'aletler',
  'hammer': 'çekiç',
  'screwdriver': 'tornavida',
  'wrench': 'anahtar',
  'pliers': 'pense',
  'saw': 'testere',
  'drill': 'matkap',
  'nail': 'çivi',
  'screw': 'vida',
  'bolt': 'cıvata',
  'ladder': 'merdiven',
  'rope': 'halat',
  'lock': 'kilit',
  'key': 'anahtar',
  'padlock': 'asma kilit',
  'hose': 'hortum',
  'bucket': 'kova',
  'broom': 'süpürge',
  'mop': 'paspas',
  'dustpan': 'faraş',
  'vacuum': 'elektrik süpürgesi',
  'vacuum cleaner': 'elektrikli süpürge',
  'iron': 'ütü',
  'ironing board': 'ütü masası',
  'washing machine': 'çamaşır makinesi',
  'dryer': 'kurutma makinesi',
  'sewing machine': 'dikiş makinesi',
  'needle': 'iğne',
  'thread': 'iplik',
  'button': 'düğme',
  'zipper': 'fermuar',
  'hanger': 'askı',
  'basket': 'sepet',
  'bin': 'çöp kutusu',
  'trash can': 'çöp tenekesi',
  'garbage': 'çöp',
  'recycling bin': 'geri dönüşüm kutusu',
  'wheelbarrow': 'el arabası',
  'shovel': 'kürek',
  'rake': 'tırmık',
  'hoe': 'çapa',
  'axe': 'balta',
  'pickaxe': 'kazma',
  'chainsaw': 'motorlu testere',
  'lawnmower': 'çim biçme makinesi',
  'sprinkler': 'fıskiye',
  'garden hose': 'bahçe hortumu',
  'watering can': 'sulama kabı',
  'plant': 'bitki',
  'tree': 'ağaç',
  'bush': 'çalı',
  'grass': 'çimen',
  'leaf': 'yaprak',
  'flower': 'çiçek',
  'rose': 'gül',
  'tulip': 'lale',
  'sunflower': 'ayçiçeği',
  'daisy': 'papatya',
  'lily': 'zambak',
  'orchid': 'orkide',
  'cactus': 'kaktüs',

  // ═══════════════════════════════════════════════════════════════════════════
  // MEDICAL & HEALTH
  // ═══════════════════════════════════════════════════════════════════════════
  'medical': 'tıbbi',
  'medicine': 'ilaç',
  'pill': 'hap',
  'capsule': 'kapsül',
  'syringe': 'şırınga',
  'bandage': 'bandaj',
  'band-aid': 'yara bandı',
  'thermometer': 'termometre',
  'stethoscope': 'steteskop',
  'wheelchair': 'tekerlekli sandalye',
  'crutch': 'koltuk değneği',
  'cane': 'baston',
  'stretcher': 'sedye',
  'hospital bed': 'hastane yatağı',
  'mask': 'maske',
  'face mask': 'yüz maskesi',
  'surgical mask': 'cerrahi maske',
  'first aid kit': 'ilk yardım çantası',
  'blood pressure monitor': 'tansiyon aleti',
  'oxygen mask': 'oksijen maskesi',
  'iv drip': 'serum',
  'x-ray': 'röntgen',
  'mri': 'mr',
  'ct scan': 'tomografi',
  'ultrasound': 'ultrason',
  'hospital': 'hastane',
  'clinic': 'klinik',
  'pharmacy': 'eczane',
  'doctor': 'doktor',
  'nurse': 'hemşire',
  'patient': 'hasta',

  // ═══════════════════════════════════════════════════════════════════════════
  // MUSICAL INSTRUMENTS
  // ═══════════════════════════════════════════════════════════════════════════
  'musical instrument': 'müzik aleti',
  'instrument': 'enstrüman',
  'piano': 'piyano',
  'guitar': 'gitar',
  'acoustic guitar': 'akustik gitar',
  'electric guitar': 'elektro gitar',
  'bass': 'bas gitar',
  'violin': 'keman',
  'viola': 'viyola',
  'cello': 'çello',
  'double bass': 'kontrabas',
  'harp': 'arp',
  'flute': 'flüt',
  'clarinet': 'klarnet',
  'oboe': 'obua',
  'saxophone': 'saksafon',
  'trumpet': 'trompet',
  'trombone': 'trombon',
  'french horn': 'korno',
  'tuba': 'tuba',
  'drum': 'davul',
  'drums': 'davullar',
  'drum kit': 'bateri',
  'cymbal': 'zil',
  'tambourine': 'tef',
  'xylophone': 'ksilofon',
  'accordion': 'akordeon',
  'harmonica': 'mızıka',
  'banjo': 'banjo',
  'ukulele': 'ukulele',
  'mandolin': 'mandolin',
  'organ': 'org',

  // ═══════════════════════════════════════════════════════════════════════════
  // BUILDINGS & PLACES
  // ═══════════════════════════════════════════════════════════════════════════
  'building': 'bina',
  'house': 'ev',
  'home': 'yuva',
  'apartment': 'daire',
  'flat': 'apartman dairesi',
  'hotel': 'otel',
  'motel': 'motel',
  'hostel': 'hostel',
  'university': 'üniversite',
  'college': 'kolej',
  'library': 'kütüphane',
  'museum': 'müze',
  'church': 'kilise',
  'mosque': 'cami',
  'temple': 'tapınak',
  'synagogue': 'sinagog',
  'palace': 'saray',
  'castle': 'kale',
  'tower': 'kule',
  'skyscraper': 'gökdelen',
  'office building': 'ofis binası',
  'factory': 'fabrika',
  'warehouse': 'depo',
  'shop': 'dükkan',
  'store': 'mağaza',
  'supermarket': 'süpermarket',
  'mall': 'alışveriş merkezi',
  'shopping center': 'alışveriş merkezi',
  'market': 'pazar',
  'restaurant': 'restoran',
  'cafe': 'kafe',
  'bar': 'bar',
  'pub': 'meyhane',
  'nightclub': 'gece kulübü',
  'cinema': 'sinema',
  'theater': 'tiyatro',
  'theatre': 'tiyatro salonu',
  'concert hall': 'konser salonu',
  'playground': 'oyun alanı',
  'zoo': 'hayvanat bahçesi',
  'aquarium': 'akvaryum',
  'beach': 'plaj',
  'bank': 'banka',
  'atm': 'bankamatik',
  'post office': 'postane',
  'police station': 'polis karakolu',
  'fire station': 'itfaiye',
  'gas station': 'benzin istasyonu',
  'petrol station': 'akaryakıt istasyonu',
  'parking lot': 'otopark',
  'garage': 'garaj',
  'airport': 'havalimanı',
  'train station': 'tren istasyonu',
  'bus station': 'otobüs terminali',
  'subway station': 'metro istasyonu',
  'port': 'liman',
  'harbor': 'liman',
  'bridge': 'köprü',
  'tunnel': 'tünel',
  'road': 'yol',
  'street': 'sokak',
  'highway': 'otoyol',
  'intersection': 'kavşak',
  'crosswalk': 'yaya geçidi',
  'sidewalk': 'kaldırım',
  'pavement': 'asfalt',
  'path': 'patika',
  'trail': 'parkur',
  'alley': 'ara sokak',

  // ═══════════════════════════════════════════════════════════════════════════
  // NATURE & OUTDOOR
  // ═══════════════════════════════════════════════════════════════════════════
  'nature': 'doğa',
  'sky': 'gökyüzü',
  'cloud': 'bulut',
  'sun': 'güneş',
  'moon': 'ay',
  'star': 'yıldız',
  'rainbow': 'gökkuşağı',
  'rain': 'yağmur',
  'snow': 'kar',
  'fog': 'sis',
  'wind': 'rüzgar',
  'storm': 'fırtına',
  'lightning': 'şimşek',
  'thunder': 'gök gürültüsü',
  'mountain': 'dağ',
  'hill': 'tepe',
  'valley': 'vadi',
  'cliff': 'uçurum',
  'cave': 'mağara',
  'rock': 'kaya',
  'stone': 'taş',
  'pebble': 'çakıl taşı',
  'sand': 'kum',
  'dirt': 'toprak',
  'mud': 'çamur',
  'dust': 'toz',
  'river': 'nehir',
  'stream': 'dere',
  'lake': 'göl',
  'pond': 'gölet',
  'ocean': 'okyanus',
  'sea': 'deniz',
  'wave': 'dalga',
  'waterfall': 'şelale',
  'spring': 'kaynak',
  'well': 'kuyu',
  'forest': 'orman',
  'jungle': 'cengel',
  'woods': 'ormanlık',
  'palm tree': 'palmiye',
  'pine tree': 'çam ağacı',
  'oak': 'meşe',
  'branch': 'dal',
  'trunk': 'gövde',
  'root': 'kök',
  'leaves': 'yapraklar',
  'petal': 'taç yaprak',
  'stem': 'sap',
  'thorn': 'diken',
  'lawn': 'çim',
  'meadow': 'çayır',
  'farm': 'çiftlik',
  'barn': 'ahır',
  'fence': 'çit',
  'gate': 'giriş kapısı',
  'desert': 'çöl',
  'island': 'ada',
  'peninsula': 'yarımada',
  'continent': 'kıta',
  'horizon': 'ufuk',
  'landscape': 'manzara',
  'scenery': 'doğal görünüm',
  'view': 'görünüm',

  // ═══════════════════════════════════════════════════════════════════════════
  // SIGNS & SYMBOLS
  // ═══════════════════════════════════════════════════════════════════════════
  'sign': 'tabela',
  'traffic sign': 'trafik işareti',
  'stop sign': 'dur işareti',
  'traffic light': 'trafik ışığı',
  'traffic signal': 'trafik sinyali',
  'street sign': 'sokak tabelası',
  'billboard': 'reklam panosu',
  'banner': 'pankart',
  'flag': 'bayrak',
  'label': 'etiket',
  'tag': 'fiyat etiketi',
  'price tag': 'ürün etiketi',
  'barcode': 'barkod',
  'qr code': 'qr kodu',
  'logo': 'logo',
  'icon': 'simge',
  'symbol': 'sembol',
  'arrow': 'ok',
  'exit sign': 'çıkış işareti',
  'entrance': 'giriş',
  'warning sign': 'uyarı işareti',
  'danger sign': 'tehlike işareti',
  'no smoking': 'sigara içilmez',
  'parking sign': 'park işareti',
  'speed limit': 'hız sınırı',
  'one way': 'tek yön',
  'no entry': 'girilmez',
  'pedestrian': 'yaya',
  'bicycle lane': 'bisiklet yolu',
  'bus stop': 'otobüs durağı',
  'taxi stand': 'taksi durağı',
  'information': 'bilgi',
  'restroom': 'tuvalet',
  'men': 'erkek',
  'women': 'kadın',
  'disabled': 'engelli',
  'handicapped': 'engelli işareti',
  'fire exit': 'yangın çıkışı',
  'fire hydrant': 'yangın musluğu',
  'fire extinguisher': 'yangın söndürücü',

  // ═══════════════════════════════════════════════════════════════════════════
  // TOYS & GAMES
  // ═══════════════════════════════════════════════════════════════════════════
  'toy': 'oyuncak',
  'doll': 'oyuncak bebek',
  'teddy bear': 'oyuncak ayı',
  'stuffed animal': 'peluş hayvan',
  'action figure': 'aksiyon figürü',
  'robot toy': 'robot oyuncak',
  'lego': 'lego',
  'building blocks': 'yapı blokları',
  'puzzle': 'yapboz',
  'board game': 'masa oyunu',
  'card game': 'kart oyunu',
  'playing cards': 'oyun kartları',
  'dice': 'zar',
  'chess': 'satranç',
  'checkers': 'dama',
  'dominoes': 'domino',
  'yo-yo': 'yo-yo',
  'top': 'topaç',
  'spinning top': 'dönen topaç',
  'balloon': 'balon',
  'bubble': 'baloncuk',
  'slide': 'kaydırak',
  'swing': 'salıncak',
  'seesaw': 'tahterevalli',
  'sandbox': 'kum havuzu',
  'trampoline': 'trambolin',
  'tricycle': 'üç tekerlekli bisiklet',
  'toy car': 'oyuncak araba',
  'toy train': 'oyuncak tren',
  'toy airplane': 'oyuncak uçak',
  'toy boat': 'oyuncak tekne',
  'beach ball': 'plaj topu',
  'rubber duck': 'kauçuk ördek',
  'water gun': 'su tabancası',
  'nerf gun': 'oyuncak tabanca',

  // ═══════════════════════════════════════════════════════════════════════════
  // MISCELLANEOUS
  // ═══════════════════════════════════════════════════════════════════════════
  'object': 'nesne',
  'thing': 'şey',
  'item': 'eşya',
  'stuff': 'malzeme',
  'material': 'materyal',
  'plastic': 'plastik',
  'metal': 'metal',
  'wood': 'ahşap',
  'wooden': 'tahta',
  'fabric': 'kumaş',
  'leather': 'deri',
  'rubber': 'kauçuk',
  'ceramic': 'seramik',
  'porcelain': 'porselen',
  'concrete': 'beton',
  'brick': 'tuğla',
  'tile': 'karo',
  'marble': 'mermer',
  'granite': 'granit',
  'gold': 'altın',
  'silver': 'gümüş',
  'copper': 'bakır',
  'bronze': 'bronz',
  'steel': 'çelik',
  'aluminum': 'alüminyum',
  'box': 'kutu',
  'package': 'paket',
  'parcel': 'koli',
  'crate': 'kasa',
  'carton': 'karton kutu',
  'sack': 'çuval',
  'bundle': 'bohça',
  'wrapper': 'ambalaj',
  'barrel': 'fıçı',
  'tank': 'tank',
  'cylinder': 'silindir',
  'sphere': 'küre',
  'cube': 'küp',
  'cone': 'koni',
  'pyramid': 'piramit',
  'circle': 'daire',
  'square': 'kare',
  'triangle': 'üçgen',
  'rectangle': 'dikdörtgen',
  'line': 'çizgi',
  'point': 'nokta',
  'corner': 'köşe',
  'edge': 'kenar',
  'surface': 'yüzey',
  'pattern': 'desen',
  'stripe': 'çizgi deseni',
  'spot': 'benek',
  'dot': 'nokta',
  'color': 'renk',
  'red': 'kırmızı',
  'blue': 'mavi',
  'green': 'yeşil',
  'yellow': 'sarı',
  'purple': 'mor',
  'pink': 'pembe',
  'brown': 'kahverengi',
  'black': 'siyah',
  'white': 'beyaz',
  'gray': 'gri',
  'grey': 'gri renk',
  'light': 'ışık',
  'dark': 'karanlık',
  'bright': 'parlak',
  'dim': 'loş',
  'shadow': 'gölge',
  'reflection': 'yansıma',
  'texture': 'doku',
  'smooth': 'pürüzsüz',
  'rough': 'pürüzlü',
  'soft': 'yumuşak',
  'hard': 'sert',
  'wet': 'ıslak',
  'dry': 'kuru',
  'hot': 'sıcak',
  'cold': 'soğuk',
  'warm': 'ılık',
  'cool': 'serin',
  'new': 'yeni',
  'old': 'eski',
  'clean': 'temiz',
  'dirty': 'kirli',
  'empty': 'boş',
  'full': 'dolu',
  'open': 'açık',
  'closed': 'kapalı',
  'big': 'büyük',
  'small': 'küçük',
  'large': 'geniş',
  'tiny': 'minik',
  'tall': 'uzun boylu',
  'short': 'kısa',
  'long': 'uzun',
  'wide': 'geniş boyutlu',
  'narrow': 'dar',
  'thick': 'kalın',
  'thin': 'ince',
  'heavy': 'ağır',
  'lightweight': 'hafif',
  'round': 'yuvarlak',
  'straight': 'düz',
  'curved': 'eğri',
  'bent': 'bükük',
  'indoor': 'iç mekan',
  'outdoor': 'dış mekan',
  'urban': 'kentsel',
  'rural': 'kırsal',
  'modern': 'modern',
  'traditional': 'geleneksel',
  'vintage': 'vintage',
  'antique': 'antika',
  'decoration': 'dekorasyon',
  'ornament': 'süs',
  'accessory': 'aksesuar',
  'equipment': 'ekipman',
  'device': 'cihaz',
  'appliance': 'ev aleti',
  'gadget': 'alet',
  'technology': 'teknoloji',
  'art': 'sanat',
  'artwork': 'sanat eseri',
  'sculpture': 'heykel',
  'statue': 'heykel',
  'monument': 'anıt',
  'landmark': 'simge yapı',
  'space': 'alan',
  'area': 'bölge',
  'zone': 'bölge',
  'region': 'yöre',
  'city': 'şehir',
  'town': 'kasaba',
  'village': 'köy',
  'neighborhood': 'mahalle',
  'district': 'ilçe',
  'country': 'ülke',
  'world': 'dünya',
  'earth': 'yeryüzü',
  'planet': 'gezegen',
  'weather': 'hava durumu',
  'climate': 'iklim',
  'temperature': 'sıcaklık',
  'summer': 'yaz',
  'autumn': 'sonbahar',
  'winter': 'kış',
  'time': 'zaman',
  'day': 'gün',
  'night': 'gece',
  'morning': 'sabah',
  'afternoon': 'öğleden sonra',
  'evening': 'akşam',
  'north': 'kuzey',
  'south': 'güney',
  'east': 'doğu',
  'west': 'batı',
  'left': 'sol',
  'right': 'sağ',
  'front': 'ön',
  'back': 'arka',
  'center': 'merkez',
  'inside': 'içinde',
  'outside': 'dışında',
  'near': 'yakın',
  'far': 'uzak',
};
